apiVersion: v1
kind: Pod
metadata:
  name: hellopodd
spec:
  containers:
  - name: ngg
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
